- id: '1771179357533'
  name: Chilled at night
  entities:
    light.ikea_lamp:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 3
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 25
      - 74
      rgb_color:
      - 255
      - 145
      - 66
      xy_color:
      - 0.566
      - 0.375
      friendly_name: Ikea lamp
      supported_features: 0
      state: 'on'
    light.lsc_smart_gold_edison_e27:
      state: 'on'
      brightness: 55
      color_temp_kelvin: 2200
    light.lampion:
      state: 'on'
      brightness: 1
      color_temp_kelvin: 2200
  icon: mdi:sofa-outline
  metadata: {}
- id: '1772041518312'
  name: Dinner party
  entities:
    light.aanrecht:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      - unknown
      - unknown
      - unknown
      - unknown
      - sunrise
      - sunset
      supported_color_modes:
      - color_temp
      - xy
      effect: None
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 2570
      color_temp: 389
      hs_color:
      - 28.696
      - 70.045
      rgb_color:
      - 255
      - 162
      - 76
      xy_color:
      - 0.539
      - 0.389
      mode: normal
      dynamics: none
      friendly_name: Aanrecht
      supported_features: 44
      state: 'on'
    light.lampion:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 76
      color_temp_kelvin: 2000
      color_temp: 500
      hs_color:
      - 30.601
      - 94.547
      rgb_color:
      - 255
      - 137
      - 14
      xy_color:
      - 0.598
      - 0.383
      friendly_name: Lampion
      supported_features: 0
      state: 'on'
    light.ikea_lamp:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 51
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 24
      - 97
      rgb_color:
      - 255
      - 107
      - 8
      xy_color:
      - 0.635
      - 0.353
      friendly_name: Ikea lamp
      supported_features: 0
      state: 'on'
  icon: mdi:food-turkey
  metadata: {}
