all:
  children:
    k3s_cluster:
      children:
        master:
          hosts:
            k3s-master:
              ansible_host: 10.0.2.10
        workers:
          hosts:
            k3s-worker-1:
              ansible_host: 10.0.2.11
            k3s-worker-2:
              ansible_host: 10.0.2.12

  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
